# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false
mappingsVersion = 2024.07.07-1.21
modMixinVersion = 0.8.5
mappingsChannel = parchment
modGroup = com.stereowalker.controllermod

## Publishing Porperties
_curseforge_id = 358633
_modrinth_id   = 2emUKbOT
## Environment Properties
_minecraft_version     = 1.21.1
_minecraft_version_min = 1.21
_minecraft_version_max = 1.22
_loader                = Forge
_loader_file           = META-INF/mods.toml
_loader_version        = 52.0.1
_loader_version_min    = 51
_loader_version_max    = 53
_unionlib_version      = 12.0.5
_unionlib_version_min  = 12.0.3
_unionlib_version_max  = 12.1.0
## Mod Properties
_mod_name          = Controller Support
_mod_id            = controllermod
_mod_version       = 9.0.3
_mod_release       = release
_mod_license       = All Rights Reserved
_mod_authors       = Stereowalker
_mod_issue_tracker = https://github.com/Stereowalker/Controller-Support-Mod/issues
_mod_page          = https://www.curseforge.com/minecraft/mc-mods/controller-mod
_mod_description   = Grants the ablility to play Minecraft with controllers and gives opportunity to those who want to play split-screen.
##Misc Properties
